In [1]:
import numpy as np

In [4]:
arr_3d = np.array([[[1, 2, 3], [4, 5, 6]],
                   [[7, 8, 9], [10, 11, 12]]])
result = np.hsplit(arr_3d, 2)
for sub_arr in result:
    print(sub_arr)

[[[1 2 3]]

 [[7 8 9]]]
[[[ 4  5  6]]

 [[10 11 12]]]


In [13]:
a = np.array([1, 2, 3, 4, 5, 6])
b = a.view().reshape(2, 3)
b[0, 1] = 11
print(a)
print(b)

[ 1 11  3  4  5  6]
[[ 1 11  3]
 [ 4  5  6]]


In [16]:
b2 = a.copy()
b2[0] = 10
print(a)
print(b2)

[ 1 11  3  4  5  6]
[10 11  3  4  5  6]


In [22]:
c = a * b2
csum = c.sum(axis = 0)
print(c)
print(csum)
print(f'sum is {csum}')

[ 10 121   9  16  25  36]
217
sum is 217


In [28]:
t = np.array([[1, 1], [2, 2]])
print(t.sum())
print(t.sum(axis=1))
t.sum(axis=0)

6
[2 4]


array([3, 3])

In [37]:
t2 = np.array([3, 4])
t3 = np.array([[3], [4]])
r1 = t * t2
r2 = t * t3
print(r1)
print(r2)
print(t2)

[[3 4]
 [6 8]]
[[3 3]
 [8 8]]
[3 4]


In [51]:
data = np.array([[1, 2], 
                 [3, 4], 
                 [5, 6]])
print(data[1:3, :])
print(data[1:3])
print(data[1:8])
print(data[1:2])

[[3 4]
 [5 6]]
[[3 4]
 [5 6]]
[[3 4]
 [5 6]]
[[3 4]]


In [52]:
data.sum(axis=0)

array([ 9, 12])

In [58]:
rng = np.random.default_rng()
a1 = rng.random(3)
print(a1)
a2 = rng.random((3, 2))
print(a2)
a3 = rng.normal(0, 1, (3, 2))
print(a2)

[0.26811007 0.70334941 0.16001023]
[[0.53556672 0.70720825]
 [0.80324925 0.59614609]
 [0.09613958 0.50712753]]
[[0.53556672 0.70720825]
 [0.80324925 0.59614609]
 [0.09613958 0.50712753]]


In [65]:
unique_values = np.unique(a1)
print(unique_values)
print(unique_values.shape)
unique_values2 = np.unique(a3)
print(unique_values2)
print(unique_values2.shape)

[0.16001023 0.26811007 0.70334941]
(3,)
[-1.61397595 -0.98905654 -0.2182064   0.09447062  0.1334136   0.17914466]
(6,)


In [68]:
print(np.unique(a3, return_index=True))
print(np.unique(a3, return_counts=True))

(array([-1.61397595, -0.98905654, -0.2182064 ,  0.09447062,  0.1334136 ,
        0.17914466]), array([5, 3, 2, 0, 4, 1]))
(array([-1.61397595, -0.98905654, -0.2182064 ,  0.09447062,  0.1334136 ,
        0.17914466]), array([1, 1, 1, 1, 1, 1]))


In [73]:
a_2d = np.array([[1, 2, 3, 4], 
                 [5, 6, 7, 8], 
                 [9, 10, 11, 12], 
                 [1, 2, 3, 4], 
                 [1, 2, 3, 5]])
unique_rows = np.unique(a_2d, axis=0)
print(unique_rows)

[[ 1  2  3  4]
 [ 1  2  3  5]
 [ 5  6  7  8]
 [ 9 10 11 12]]
