In [1]:
import numpy as np

In [4]:
a = np.array([1, 2, 3, 4, 5, 6])
np.save('April_12', a)

In [7]:
b = np.load('April_12.npy')
print('a:\n', a)
print('b:\n', b)

a:
 [1 2 3 4 5 6]
b:
 [1 2 3 4 5 6]


In [16]:
np.savetxt('April_12.csv', a, header="abc", footer = "cba", delimiter = "1")

In [17]:
b2 = np.loadtxt('April_12.csv')
print('b2: \n', b2)

b2: 
 [1. 2. 3. 4. 5. 6.]
