In [1]:
import numpy as np

In [8]:
print(np.diag([1, 2, 3, 4]))
print(np.diag([1, 2, 3], 1))
a = np.array([[1, 2], [3, 4]])
print(np.diag(a))

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
[[0 1 0 0]
 [0 0 2 0]
 [0 0 0 3]
 [0 0 0 0]]
[1 4]


In [13]:
print(np.vander(np.linspace(0, 2, 5), 2))
print(np.vander([1, 2, 3, 4], 0))
print(np.vander([1, 2, 3, 4], 2))
print(np.vander([1, 2, 3, 4], 4))

[[0.  1. ]
 [0.5 1. ]
 [1.  1. ]
 [1.5 1. ]
 [2.  1. ]]
[]
[[1 1]
 [2 1]
 [3 1]
 [4 1]]
[[ 1  1  1  1]
 [ 8  4  2  1]
 [27  9  3  1]
 [64 16  4  1]]


In [16]:
print(np.indices((3, 4)))

[[[0 0 0 0]
  [1 1 1 1]
  [2 2 2 2]]

 [[0 1 2 3]
  [0 1 2 3]
  [0 1 2 3]]]
