In [1]:
import numpy as np

In [11]:
a = np.array([[[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]],
              [[11, 22, 33],
               [44, 55, 66],
               [77, 88, 99]]])
data = a.reshape(3, 2, -1)
print(a)
print(data)
print("tped data:\n", data.T)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 22 33]
  [44 55 66]
  [77 88 99]]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [11 22 33]]

 [[44 55 66]
  [77 88 99]]]
tp data:
 [[[ 1  7 44]
  [ 4 11 77]]

 [[ 2  8 55]
  [ 5 22 88]]

 [[ 3  9 66]
  [ 6 33 99]]]


In [16]:
data2 = data.transpose((1, 0, 2))
print("tped data2:\n", data2)

tped data2:
 [[[ 1  2  3]
  [ 7  8  9]
  [44 55 66]]

 [[ 4  5  6]
  [11 22 33]
  [77 88 99]]]


In [25]:
flip = np.flip(data2)
flip2 = np.flip(data2, (0, 1))
print('org data:', data2)
print("fped data:\n", flip)
print("fped data2:\n", flip2)

org data: [[[ 1  2  3]
  [ 7  8  9]
  [44 55 66]]

 [[ 4  5  6]
  [11 22 33]
  [77 88 99]]]
fped data:
 [[[99 88 77]
  [33 22 11]
  [ 6  5  4]]

 [[66 55 44]
  [ 9  8  7]
  [ 3  2  1]]]
fped data2:
 [[[77 88 99]
  [11 22 33]
  [ 4  5  6]]

 [[44 55 66]
  [ 7  8  9]
  [ 1  2  3]]]


In [39]:
flt = flip2.flatten()
flt2 = flip2.ravel()
print("org flp2: \n", flip2)
print("flt:\n", flt)
print("flt2:\n", flt2)
flt2[1] = -99
print("org flp2: \n", flip2)
print("reflt:\n", flt)
print("reflt2:\n", flt2)
print("data2:\n", data)

org flp2: 
 [[[77 88 99]
  [11 22 33]
  [ 4  5  6]]

 [[44 55 66]
  [ 7  8  9]
  [ 1  2  3]]]
flt:
 [77 88 99 11 22 33  4  5  6 44 55 66  7  8  9  1  2  3]
flt2:
 [77 88 99 11 22 33  4  5  6 44 55 66  7  8  9  1  2  3]
org flp2: 
 [[[77 88 99]
  [11 22 33]
  [ 4  5  6]]

 [[44 55 66]
  [ 7  8  9]
  [ 1  2  3]]]
reflt:
 [77 88 99 11 22 33  4  5  6 44 55 66  7  8  9  1  2  3]
reflt2:
 [ 77 -99  99  11  22  33   4   5   6  44  55  66   7   8   9   1   2   3]
data2:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [11 22 33]]

 [[44 55 66]
  [77 88 99]]]


In [37]:
a = np.array([[1, 2],
              [3, 4]])
flta = a.ravel()

print("a \n", a)
print("flta \n", flta)

flta[1] = -99
print("a \n", a)
print("flta \n", flta)

a 
 [[1 2]
 [3 4]]
flta 
 [1 2 3 4]
a 
 [[  1 -99]
 [  3   4]]
flta 
 [  1 -99   3   4]


In [40]:
## 注意这个ravel创造的是视图，是对原数据的引用，改变ravel()后的数组会影响前面所有数组
a = np.array([[[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]],
              [[11, 22, 33],
               [44, 55, 66],
               [77, 88, 99]]])
data = a.reshape(3, 2, -1)
t1 = data.ravel()
t1[1] = -99
print("a \n", a)
print("data \n", data)
print("t1 \n", t1)

a 
 [[[  1 -99   3]
  [  4   5   6]
  [  7   8   9]]

 [[ 11  22  33]
  [ 44  55  66]
  [ 77  88  99]]]
data 
 [[[  1 -99   3]
  [  4   5   6]]

 [[  7   8   9]
  [ 11  22  33]]

 [[ 44  55  66]
  [ 77  88  99]]]
t1 
 [  1 -99   3   4   5   6   7   8   9  11  22  33  44  55  66  77  88  99]


In [42]:
## 注意这个ravel()创造的是copy,改变ravel()后的数组内容不影响原来的数组but why?
a = np.array([[[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]],
              [[11, 22, 33],
               [44, 55, 66],
               [77, 88, 99]]])
data = a.reshape(3, 2, -1)
data2 = data.transpose((1, 0, 2))##只多了transpose()
t1 = data2.ravel()
t1[1] = -99
print("a \n", a)
print("data \n", data)
print("data2 \n", data2)
print("t1 \n", t1)

a 
 [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 22 33]
  [44 55 66]
  [77 88 99]]]
data 
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [11 22 33]]

 [[44 55 66]
  [77 88 99]]]
data2 
 [[[ 1  2  3]
  [ 7  8  9]
  [44 55 66]]

 [[ 4  5  6]
  [11 22 33]
  [77 88 99]]]
t1 
 [  1 -99   3   7   8   9  44  55  66   4   5   6  11  22  33  77  88  99]


In [47]:
def double(a):
  '''Return a * 2'''
  return a * 2
double??

Signature: double(a)
Source:   
def double(a):
  '''Return a * 2'''
  return a * 2
File:      c:\users\12162\appdata\local\temp\ipykernel_25136\421522582.py
Type:      function